spring:
  # DATASOURCE
  datasource:
    url: jdbc:postgresql://localhost:5432/dms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA / HIBERNATE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgresql

  servlet:
    multipart:
      # UPLOAD LIMITS
      max-file-size: ${MAX_FILE_SIZE:32MB}
      max-request-size: ${MAX_REQUEST_SIZE:32MB}