--- # Default profile 
spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:32MB}
      max-request-size: ${MAX_REQUEST_SIZE:256MB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      platform: postgresql
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
--- # Development profile (uses Postgres)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/dms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
--- # Integration profile (uses H2)
spring:
  config:
    activate:
      on-profile: integration
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: h2

logging:
  level:
    at.fhtw.rest: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: OFF