--- # Default (Development) Profile (uses Postgres)
spring:
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 256MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/dms
    username: postgres
    password: postgres
logging:
  level:
    org.springframework.web: INFO
    at.fhtw.rest: INFO
    org.zalando.logbook: TRACE
logbook:
  format.style: http
  write.max-body-size: 10000

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:documents}

--- # CI/CD Integration Profile (uses H2)
spring:
  config:
    activate:
      on-profile: integration
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false
  sql:
    init:
      platform: h2
