openapi: "3.0.0"
info:
  title: Document Management System API
  version: 0.0.1

paths:
  /api/v1/status:
    get:
      tags: [Status]
      summary: API Health Status
      operationId: getStatus
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "Document Management System API is alive."

  /api/v1/documents:
    post:
      tags: [Document]
      summary: Upload a document
      operationId: uploadDocument
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [file]
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201": { description: Created }
        "400": { description: Bad Request }