openapi: "3.0.0"
info:
  title: Document Management System API
  version: 0.0.1

servers:
  - url: http://localhost:8080

paths:
  /api/v1/status:
    get:
      tags: [Status]
      summary: API Health Status
      operationId: getStatus
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "Alive."

  /api/v1/documents:
    get:
      tags: [Document]
      summary: List documents
      operationId: getDocuments
      responses:
        "200":
          description: Documents retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'

    post:
      tags: [Document]
      summary: Upload a document
      operationId: uploadDocument
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [file]
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: Document created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        "400": { description: Bad Request }

  /api/v1/documents/{id}:
    get:
      tags: [Document]
      summary: Get document by id
      operationId: getDocumentById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Document retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        "404": { description: Not Found }

components:
  schemas:
    DocumentDto:
      type: object
      required: [id, title]
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
