services:
  rest:
    build:
      context: rest
    container_name: rest
    environment:
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 64MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 256MB
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  adminer:
    image: adminer:5.4.0
    container_name: adminer
    depends_on: [ db ]
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "9090:8080"

  ui:
    build:
      context: ui
    container_name: ui
    depends_on: [ rest ]
    ports:
      - "80:80"