services:
  rest:
    build:
      context: rest
    container_name: rest
    depends_on:
      - db
      - rabbitmq
    environment:
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 64MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 256MB
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "8080:8080"

  ocr:
    build:
      context: ocr
    container_name: ocr
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  adminer:
    image: adminer:5.4.0
    container_name: adminer
    depends_on: [ db ]
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "9090:8080"

  ui:
    build:
      context: ui
    container_name: ui
    depends_on: [ rest ]
    ports:
      - "80:80"
