services:
  rest:
    build:
      context: ../rest
    container_name: rest
    ports:
      - "8080:8080"

  db:
    image:
      postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"